caziliot/Hometastic

app/controllers/application_controller.rb, app/controllers/booking_requests_controller.rb, app/controllers/flats_controller.rb, app/controllers/pages_controller.rb, app/models/booking_request.rb, app/models/flat.rb, app/models/user.rb
=> done basic validations

app/models/message.rb, app/models/review.rb
=> Messages validations

app/controllers/flats_controller.rb, app/controllers/registrations_controller.rb, app/models/flat.rb, app/views/flats/new.html.erb, app/views/flats/show.html.erb, config/routes.rb
Hi guys! So this is what can we do/see now:
1) Sign up form
2) After we sing up we are redirect to the new flat form, so that we can create our flat right aways
3) And after that we are redirect to the flat show page (but in the future we can redirect somewhere else if we want)
We can also see the reviews now (example below from the seeds)
=> feat: complete path from sign up to flat show page (also the reviews are showing)

Gemfile, app/assets/stylesheets/application.scss, app/controllers/booking_requests_controller.rb, app/controllers/flats_controller.rb, app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/models/available_month.rb, app/models/booking_request.rb, app/models/flat.rb, app/models/user.rb, app/views/components/_card.html.erb, app/views/flats/show.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb, db/migrate/20220222193132_remove_price_from_booking_request.rb, db/migrate/20220222193500_add_price_requester_to_booking_request.rb, db/migrate/20220222193958_add_columns_to_booking_requests.rb, db/migrate/20220222202424_create_available_months.rb, db/migrate/20220224061256_change_columns_from_booking_requests.rb, db/migrate/20220224071319_add_taken_to_available_months.rb, db/migrate/20220225185228_add_default_to_status_from_booking_request.rb, db/schema.rb, db/seeds.rb, package.json, test/models/available_month_test.rb, yarn.lock
Things that has been changed:
- Model change to booking request and migration
- Added Available month table references:flat
- Added flatpickr and validate data gem
- yarn install needed
- prices and service fee calculations for the booking
- added a dashboard sample page showing outgoing and incoming
- dashboard controller
- Booking Request controller being able to create
=> Booking requests feature

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/views/components/_buttons.html.erb, app/views/layouts/application.html.erb
=> Feat: buttons design

app/assets/stylesheets/components/_searchbar.scss, app/views/components/_search_bar.html.erb
=> Search Icon completed

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/views/components/_footer.html.erb, app/views/layouts/application.html.erb, db/schema.rb, yarn.lock
the icon changes to pink and slides down let me know if you need something change.
[
](url)
=> completed footer

app/controllers/booking_requests_controller.rb, app/models/booking_request.rb, app/models/flat.rb, app/views/pages/dashboard.html.erb, config/routes.rb, db/migrate/20220226130911_add_payment_columns_to_booking_requests.rb, db/schema.rb, yarn.lock
Now the accept is working for both sides of the user.
=> Booking accet

app/models/amenity.rb, app/models/flat.rb, db/migrate/20220226105533_create_amenities.rb, db/schema.rb, test/models/amenity_test.rb, yarn.lock
Created the amenity table and done associations and validations
=> feat: amenities

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_home.scss, app/assets/stylesheets/config/_general.scss, app/views/components/_navbar.html.erb
=> navbar links done, background white added to body

Gemfile.lock, app/controllers/application_controller.rb, app/controllers/flats_controller.rb, app/models/user.rb, app/views/components/_flat_form.html.erb, app/views/components/_navbar.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/flats/index.html.erb, db/schema.rb, db/seeds.rb
Now the user can upload the avatar
i also change something in the seed so you need to rails db:seed
i also add the flat name input in the flat form (it was missing)
=> feat: user picture

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_log_in_form.scss, app/views/components/_log_in_form.html.erb, app/views/devise/sessions/new.html.erb
and finally this is the log in form
=> feat: log in form

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_sign_up_form.scss, app/views/components/_sign_up_form.html.erb, app/views/devise/registrations/new.html.erb
Hi guys! I just did a very basic form for when we create a new user
=> feat: sign up form

app/assets/stylesheets/components/_amenity_form.scss, app/assets/stylesheets/components/_index.scss, app/views/amenities/new.html.erb, app/views/components/_amenity_form.html.erb
and this is the (also basic) form for when we want to add an amenity
=> feat: amenity form

app/assets/stylesheets/components/_index.scss, app/controllers/chat_rooms_controller.rb, app/models/flat.rb, app/models/user.rb, app/views/chat_rooms/index.html.erb, app/views/chat_rooms/show.html.erb, app/views/components/_navbar.html.erb, app/views/flats/show.html.erb, app/views/pages/dashboard.html.erb, config/routes.rb
Now the app can:
- guide a user withou the need of pressing back
- go to the chats index page
- dashboard with buttons
- validation of existance of chats before creating one
- created method for finding a specific chat.
=> Feature: User journey defined

app/javascript/plugins/init_autocomplete.js, app/views/components/_flat_form.html.erb
Now the app can require actual addresses and choose a real city from the selection. 
Only real cities are gonna be created through Alguila.
=> Places Js new flat form

app/controllers/flats_controller.rb
User will only have one flat, would be redirected to its own flat show page if trying to do so.
=> Validation: User can create a second flat

app/controllers/booking_requests_controller.rb, app/models/user.rb, app/views/pages/dashboard.html.erb, config/routes.rb
I put the decline button and made some changes in the logic so that we actually decline and cancel a booking request.
=> feat: we can now decline a booking request

app/assets/stylesheets/components/_dashcard.scss, app/assets/stylesheets/components/_index.scss, app/views/components/_dashcard.html.erb, app/views/pages/dashboard.html.erb
=> Completed dashcard

app/assets/stylesheets/config/_general.scss, app/views/flats/show.html.erb
=> Flat show layout

app/assets/stylesheets/components/_edit_user_form.scss, app/assets/stylesheets/components/_index.scss, app/views/components/_edit_user_form.html.erb, app/views/devise/registrations/edit.html.erb
Goodmorning guys!
I just did a basic form design for the edit user page.
=> feat: edit user form

app/assets/stylesheets/components/_confirm_form.scss, app/assets/stylesheets/components/_index.scss, app/views/booking_requests/confirm.html.erb, app/views/components/_confirm_form.html.erb
this is a little form when we pay
=> feat: pay form

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_pay.scss, app/views/booking_requests/pay.html.erb
I also tried to style a little bit the "congratulation" page..
we are redirect here after we pay
=> feat: confirm page design

app/assets/stylesheets/components/_dashcard.scss, app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/models/user.rb, app/views/components/_dashcard.html.erb, app/views/components/_dashcard_in.html.erb, app/views/components/_search_bar.html.erb, app/views/pages/dashboard.html.erb
I have implemented MArcy's cards and add them to the dashboard with the actual info. 
Also added a way to calculate the amount of total swaps (finished stays) that a user has had. 
Still some front end missing to adapt, but in general worked just fine. 
Also change the avatar-large class that Marcy was using just to adapt it.
=> feature: Dashboard Cards with back end logic

app/javascript/packs/application.js, app/javascript/plugins/flatpickr.js, app/views/components/_dashcard.html.erb, app/views/components/_search_bar.html.erb, app/views/pages/dashboard.html.erb
I structured the search bar implementing Joaquins info and a little bit of marcys code, still important to understand what it was done, and how to remove algolia icons. Flatpickr implemented, and places js. 
Places Js generates a button automatically, and the css has a button format somewhere that I aint sure where it is.
=> Format searchbar

app/assets/stylesheets/components/_flat_summary.scss, app/assets/stylesheets/components/_index.scss, app/views/components/_flat_summary.html.erb, app/views/flats/index.html.erb, app/views/pages/dashboard.html.erb
Flat summary card that goes on the dashboard.
=> Flat summary

app/assets/stylesheets/components/_confirm_form.scss, app/views/components/_confirm_form.html.erb
Hello guys!
I added some validations when we pay:
- credit card number, expiracy date and cvv must be present;
- creditcard number must be 16 digits;
- expiracy date must be in the format MM/YY (e.g. 03/23);
- CVV must be 3 or 4 digits
=> feat: payment validations

app/assets/stylesheets/components/_card.scss
cards have a nice zoom in when you hover over on flat index page
=> zoom in cards hover

app/assets/stylesheets/components/_card.scss, app/views/components/_reviews.html.erb, app/views/flats/show.html.erb
Hello there!
I made a simple design for the reviews
=> feat: Reviews show

app/models/user.rb, app/views/chat_rooms/index.html.erb, app/views/components/_chat_bubble.html.erb
Integrated Marcy's chat cards to the index page of the chats.
=> feature: Chat cards

app/assets/stylesheets/components/_chat_bubble.scss, app/assets/stylesheets/components/_pay.scss, app/controllers/chat_rooms_controller.rb, app/models/user.rb, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/index.html.erb, app/views/chat_rooms/show.html.erb, app/views/components/_chat_bubble.html.erb
Ahora el show page tiene los cards y el chat en la misma página.
=> Chat integration

app/assets/stylesheets/components/_card.scss, app/views/components/_search_bar.html.erb, app/views/flats/index.html.erb
searchbar had a div more, now index page is rendering well
=> flat index layout fixed

app/assets/stylesheets/components/_chat_bubble.scss, app/assets/stylesheets/components/_pay.scss, app/controllers/chat_rooms_controller.rb, app/javascript/channels/chat_room_channel.js, app/javascript/packs/application.js, app/javascript/plugins/init_chat_listener.js, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/show.html.erb, app/views/messages/_message.html.erb
Now we can navigate through the chats and send messages without reloading the page.
=> Chat javascript

app/views/components/_dashcard.html.erb, app/views/components/_dashcard_in.html.erb, app/views/components/_stay_status.html.erb, app/views/components/_stay_status_in.html.erb
=> feat: Dashboard state journey

app/assets/stylesheets/components/_dashcard.scss, app/assets/stylesheets/components/_flat_summary.scss, app/assets/stylesheets/config/_general.scss, app/views/chat_rooms/index.html.erb, app/views/components/_dashcard.html.erb, app/views/components/_dashcard_in.html.erb, app/views/components/_flat_summary.html.erb, app/views/flats/show.html.erb, app/views/pages/dashboard.html.erb
=> Dashbooard frontend

app/views/flats/show.html.erb
Added months available temporaly to the show page on the description
=> added months available to show page

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_messages.scss, app/controllers/chat_rooms_controller.rb, app/javascript/channels/chat_room_channel.js, app/models/chat_room.rb, app/models/flat.rb, app/models/user.rb, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/show.html.erb, app/views/components/_chat_bubble.html.erb, app/views/flats/show.html.erb, app/views/messages/_message.html.erb, db/migrate/20220313190635_add_user_to_chat_rooms.rb, db/schema.rb, db/seeds.rb
Changed the database structure, now updated on the db diagram. 
Added a user reference to the chat so it is easier to find which chat belongs to whom. 
Validation on picture
Now the index on the left displays completely the chats incoming and outgoing
Chat with scroll now
all_chats working properly and model has a outgoing_chats alias to represent the chats sent to flats from the current_user
=> Chats improvement

app/assets/stylesheets/components/_amenity_form.scss, app/controllers/amenities_controller.rb, app/javascript/controllers/amenities_selector_controller.js, app/javascript/controllers/hello_controller.js, app/javascript/controllers/index.js, app/javascript/packs/application.js, app/javascript/plugins/init_chat_listener.js, app/models/flat.rb, app/models/general_amenity.rb, app/views/amenities/_success.html.erb, app/views/components/_amenity_form.html.erb, app/views/flats/show.html.erb, db/migrate/20220314000148_create_general_amenities.rb, db/schema.rb, db/seeds.rb, package.json, test/models/general_amenity_test.rb, yarn.lock
Now we can select the amenities and edit them on the spot. 
Beware: Not to rename the css classes, as the Stimulus is connected to them, add new classes, but refrain from renaming the css classes. 
Needed to yarn install and db:seed for it to work locally.
=> Feature: Amenities selection

app/assets/config/manifest.js, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_show.scss, app/controllers/available_months_controller.rb, app/javascript/controllers/hello_controller.js, app/javascript/controllers/show_controller.js, app/views/components/_available_form.html.erb, app/views/components/_footer.html.erb, app/views/flats/_month_p.html.erb, app/views/flats/show.html.erb, db/schema.rb
Now the validations on the available month are back on working together with the javascript. 
Display and hide available months form. 
add available month to the show page. 
errors from validations show to the form
=> Validation available form

app/assets/stylesheets/components/_pay.scss, app/views/booking_requests/pay.html.erb, app/views/flats/show.html.erb, db/schema.rb
added padding, margin and link_to link place inside the box.
=> Success  pay message

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/config/_general.scss, app/controllers/booking_requests_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/javascript/plugins/init_mapbox.js, app/models/flat.rb, app/views/booking_requests/show.html.erb, app/views/components/_flat_form.html.erb, app/views/components/_map.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20220314094014_add_coordinates_to_flats.rb, db/schema.rb, db/seeds.rb, package.json, yarn.lock
now we have a map for the flat in the booking show
=> feat: Map!

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_chat_bubble.scss, app/assets/stylesheets/components/_messages.scss, app/assets/stylesheets/config/_general.scss, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/show.html.erb, app/views/components/_chat_bubble.html.erb, app/views/messages/_message.html.erb
=> chat layout improved

app/views/components/_reviews.html.erb
now we show the reviews only if there are any:
=> feat: show if reviews present

app/views/booking_requests/confirm.html.erb, app/views/components/_confirm_form.html.erb, app/views/components/_edit_user_form.html.erb, app/views/components/_flat_form.html.erb, app/views/components/_log_in_form.html.erb, app/views/components/_sign_up_form.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
I moved some links so that they are not all over the place hehe
when we sign up:
when we log in:
when we edit the user:
and also some rearrangement when we pay:
=> design: links rearranged

app/assets/stylesheets/components/_chat_bubble.scss, app/javascript/plugins/init_chat_listener.js, app/models/booking_request.rb, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/show.html.erb, app/views/components/_chat_bubble.html.erb, db/seeds.rb
Chat scrolls down and also changes title and color.
=> javascript on chat

app/assets/stylesheets/components/_booking.scss, app/assets/stylesheets/components/_search_bar.scss, app/javascript/controllers/show_controller.js, app/views/components/_available_form.html.erb, db/seeds.rb
=> feature: seeds new

app/views/layouts/application.html.erb, public/404.html, public/500.html
i changed the title tag and basic customization of the 404 and 500 pages
=> title tag, 404 and 500 page

app/models/flat.rb, app/views/components/_flat_summary.html.erb
in case there are no reviews at all:
=> feat: add if statement

app/assets/stylesheets/components/_search_bar.scss, app/controllers/booking_requests_controller.rb, app/controllers/reviews_controller.rb, app/models/available_month.rb, app/models/flat.rb, app/views/booking_requests/show.html.erb, app/views/components/_flat_summary.html.erb, app/views/components/_search_bar.html.erb, app/views/flats/index.html.erb, config/routes.rb, db/seeds.rb
Seed feature changed to more realistic seeds. 
Review form added to the booking show page, and validated if finished and if more than 1.
=> feature: Seed and reviews features

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_messages.scss, app/assets/stylesheets/config/_general.scss, app/views/chat_rooms/show.html.erb, app/views/components/_chat_bubble.html.erb, app/views/components/_navbar.html.erb, app/views/components/_reviews.html.erb, app/views/components/_stay_status.html.erb, app/views/components/_stay_status_in.html.erb, app/views/pages/dashboard.html.erb
New hover color when hovering over the dashboar buttons and log in and sign up (those where still underlining
=> Front-end: changed button decoration on Dashboard and log in button

app/assets/stylesheets/config/_general.scss, app/views/chat_rooms/_chat_show.html.erb, app/views/components/_chat_bubble.html.erb
=> feature: link on chat

Gemfile, Gemfile.lock, app/models/user.rb, app/views/components/_flat_form.html.erb
Installed new Gem to validate email formatting with higher precision. 
Added an explanatory message to the flat form.
=> validation of emails to sign up

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_chat_bubble.scss, app/assets/stylesheets/components/_messages.scss, app/assets/stylesheets/config/_general.scss, app/assets/stylesheets/pages/chat_layout.scss, app/views/chat_rooms/_chat_layout.html.erb, app/views/chat_rooms/_chat_show.html.erb, app/views/chat_rooms/show.html.erb
The chat layout is corrected, code has been refactored and the form to write messages is sticky to the bottom so is independent to the screen size. 
You can change the size of the screen and the layout would mostly remain, except in very small screens.
=> Feature: Chat layout and sticky form 
